#!/usr/bin/env ruby
require 'rubygems'
require 'dm-core'
require 'dm-migrations'

# Connect to DB 
DataMapper.setup(:default, $db_url)
# Include all models
Dir["app/models/*.rb"].each { |file| require file }
# Reset tables
DataMapper.finalize
DataMapper.auto_upgrade!

