#!/usr/bin/env ruby
require 'rubygems'
require 'dm-core'

# Include all models
Dir["app/models/*.rb"].each { |file| require file }
# Connect to DB 
DataMapper.setup(:default, $db_url)
# Reset tables
DataMapper.auto_migrate!

